# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z2.xdc

# Block Designs: bd/secure_soc/secure_soc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc || ORIG_REF_NAME==secure_soc} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_aes_axi_periph_0_2/secure_soc_aes_axi_periph_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_aes_axi_periph_0_2 || ORIG_REF_NAME==secure_soc_aes_axi_periph_0_2} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_smartconnect_0_3/secure_soc_smartconnect_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_smartconnect_0_3 || ORIG_REF_NAME==secure_soc_smartconnect_0_3} -quiet] -quiet

# Block Designs: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/bd_ebbb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_0/bd_ebbb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_1/bd_ebbb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_2/bd_ebbb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_3/bd_ebbb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_4/bd_ebbb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_5/bd_ebbb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_6/bd_ebbb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_7/bd_ebbb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_8/bd_ebbb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_9/bd_ebbb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_10/bd_ebbb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_11/bd_ebbb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_12/bd_ebbb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/secure_soc/ip/secure_soc_bus_axi_periph_0_5/secure_soc_bus_axi_periph_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_bus_axi_periph_0_5 || ORIG_REF_NAME==secure_soc_bus_axi_periph_0_5} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_clk_wiz_0_0 || ORIG_REF_NAME==secure_soc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_ila_0_0/secure_soc_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_ila_0_0 || ORIG_REF_NAME==secure_soc_ila_0_0} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_ila_1_0/secure_soc_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_ila_1_0 || ORIG_REF_NAME==secure_soc_ila_1_0} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_ila_2_0/secure_soc_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_ila_2_0 || ORIG_REF_NAME==secure_soc_ila_2_0} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_ila_3_0/secure_soc_ila_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_ila_3_0 || ORIG_REF_NAME==secure_soc_ila_3_0} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_util_vector_logic_0_2/secure_soc_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_util_vector_logic_0_2 || ORIG_REF_NAME==secure_soc_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/secure_soc/ip/secure_soc_proc_sys_reset_1_0/secure_soc_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==secure_soc_proc_sys_reset_1_0 || ORIG_REF_NAME==secure_soc_proc_sys_reset_1_0} -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_1/bd_ebbb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_5/bd_ebbb_s00a2s_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_6/bd_ebbb_sarn_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_7/bd_ebbb_srn_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_8/bd_ebbb_sawn_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_9/bd_ebbb_swn_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_10/bd_ebbb_sbn_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_11/bd_ebbb_m00s2a_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_smartconnect_0_3/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_smartconnect_0_3 || ORIG_REF_NAME==secure_soc_smartconnect_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_clk_wiz_0_0 || ORIG_REF_NAME==secure_soc_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_clk_wiz_0_0 || ORIG_REF_NAME==secure_soc_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_0_0 || ORIG_REF_NAME==secure_soc_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_0_0 || ORIG_REF_NAME==secure_soc_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_0_0/secure_soc_ila_0_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_1_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_1_0 || ORIG_REF_NAME==secure_soc_ila_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_1_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_1_0 || ORIG_REF_NAME==secure_soc_ila_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_1_0/secure_soc_ila_1_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_2_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_2_0 || ORIG_REF_NAME==secure_soc_ila_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_2_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_2_0 || ORIG_REF_NAME==secure_soc_ila_2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_2_0/secure_soc_ila_2_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_3_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_3_0 || ORIG_REF_NAME==secure_soc_ila_3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_3_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_ila_3_0 || ORIG_REF_NAME==secure_soc_ila_3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_ila_3_0/secure_soc_ila_3_0_ooc.xdc

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/ip/secure_soc_proc_sys_reset_1_0/secure_soc_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==secure_soc_proc_sys_reset_1_0 || ORIG_REF_NAME==secure_soc_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/llia622/ibex_hello_world/ibex_hello_world.gen/sources_1/bd/secure_soc/secure_soc_ooc.xdc
