# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/llia622/ibex_hello_world/ibex_hello_world.runs/synth_1/pynq_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/llia622/ibex_hello_world/ibex_hello_world.cache/wt [current_project]
set_property parent.project_path /home/llia622/ibex_hello_world/ibex_hello_world.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/llia622/.Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo /home/llia622/ibex_hello_world/ibex_hello_world.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_flop_macros.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert_dummy_macros.svh
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert_sec_cm.svh
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_dv_dv_fcov_macros_0/dv_fcov_macros.svh
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_util_memload_0/rtl/prim_util_memload.svh
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_util_get_scramble_params_0/rtl/prim_util_get_scramble_params.svh
}
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_flop_macros.sv]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert_dummy_macros.svh]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert_sec_cm.svh]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_assert_0.1/rtl/prim_assert.sv]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_dv_dv_fcov_macros_0/dv_fcov_macros.svh]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_util_memload_0/rtl/prim_util_memload.svh]
set_property file_type "Verilog Header" [get_files /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_util_get_scramble_params_0/rtl/prim_util_get_scramble_params.svh]
read_mem /home/llia622/ibex/examples/sw/simple_system/hello_test/hello.vmem
read_verilog -library xil_defaultlib -sv {
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_sim_shared_0/rtl/bus.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_pkg_0.1/rtl/ibex_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_alu.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_branch_predict.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_compressed_decoder.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_controller.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_core.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_counter.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_cs_registers.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_csr.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_decoder.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_dummy_instr.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_ex_block.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_fetch_fifo.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_icache_0.1/rtl/ibex_icache.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_id_stage.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_if_stage.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_load_store_unit.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_lockstep.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_fast.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_slow.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_pmp.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_prefetch_buffer.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_ff.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_fpga.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_latch.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_ram_1p_pkg_0/rtl/prim_ram_1p_pkg.sv
  /home/llia622/ibex/examples/simple_system/rtl/ibex_simple_system.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_top.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_wb_stage.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_and2_0/rtl/prim_and2.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_buf_0/rtl/prim_buf.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_cipher_pkg_0.1/rtl/prim_cipher_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_clock_gating_0/rtl/prim_clock_gating.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_clock_mux2_0/rtl/prim_clock_mux2.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_count_0/rtl/prim_count_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_count_0/rtl/prim_count.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_flop_0/rtl/prim_flop.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_lfsr_0.1/rtl/prim_lfsr.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_mubi_pkg_0.1/rtl/prim_mubi_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_onehot_check_0/rtl/prim_onehot_check.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_onehot_0/rtl/prim_onehot_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_onehot_0/rtl/prim_onehot_mux.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_cipher_0/rtl/prim_prince.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_ram_1p_0/rtl/prim_ram_1p.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_util_0.1/rtl/prim_util_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_ram_1p_adv_0.1/rtl/prim_ram_1p_adv.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_ram_1p_scr_0.1/rtl/prim_ram_1p_scr.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_ram_2p_pkg_0/rtl/prim_ram_2p_pkg.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_generic_ram_2p_0/rtl/prim_ram_2p.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_dec.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_dec.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_dec.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_dec.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_dec.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_enc.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_prim_cipher_0/rtl/prim_subst_perm.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_sim_shared_0/rtl/ram_2p.sv
  /home/llia622/ibex/build/lowrisc_ibex_ibex_simple_system_0/sim-verilator/src/lowrisc_ibex_sim_shared_0/rtl/timer.sv
}
read_verilog -library ibex -sv /home/llia622/ibex_hello_world/ibex_hello_world.srcs/sources_1/new/pynq_wrapper.sv
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/llia622/ibex_hello_world/ibex_hello_world.srcs/constrs_1/new/pynq_z2.xdc
set_property used_in_implementation false [get_files /home/llia622/ibex_hello_world/ibex_hello_world.srcs/constrs_1/new/pynq_z2.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/llia622/ibex_hello_world/ibex_hello_world.srcs/utils_1/imports/synth_1/pynq_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top pynq_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pynq_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file pynq_wrapper_utilization_synth.rpt -pb pynq_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
