vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/xlconstant_v1_1_10
vlib questa_lib/msim/proc_sys_reset_v5_0_17
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_35
vlib questa_lib/msim/axi_vip_v1_1_21
vlib questa_lib/msim/util_vector_logic_v2_0_5

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap xlconstant_v1_1_10 questa_lib/msim/xlconstant_v1_1_10
vmap proc_sys_reset_v5_0_17 questa_lib/msim/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_35 questa_lib/msim/axi_register_slice_v2_1_35
vmap axi_vip_v1_1_21 questa_lib/msim/axi_vip_v1_1_21
vmap util_vector_logic_v2_0_5 questa_lib/msim/util_vector_logic_v2_0_5

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/llia622/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"/home/llia622/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/llia622/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/llia622/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/home/llia622/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ipshared/c06d/hdl/aes_axi_periph_slave_lite_v1_0_S00_AXI.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ipshared/c06d/9abd/g_funct.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/inv_s_box.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/AES_decrypt.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/AES_encrypt.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/s_box.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/key_expansion.sv" \
"../../../bd/secure_soc/ipshared/c06d/9abd/AES.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ipshared/c06d/hdl/aes_axi_periph.v" \
"../../../bd/secure_soc/ip/secure_soc_aes_axi_periph_0_2/sim/secure_soc_aes_axi_periph_0_2.v" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/sim/bd_ebbb.v" \

vlog -work xlconstant_v1_1_10 -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_0/sim/bd_ebbb_one_0.v" \

vcom -work proc_sys_reset_v5_0_17 -64 -93  \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_1/sim/bd_ebbb_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_2/sim/bd_ebbb_s00mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_3/sim/bd_ebbb_s00tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_4/sim/bd_ebbb_s00sic_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_5/sim/bd_ebbb_s00a2s_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_6/sim/bd_ebbb_sarn_0.sv" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_7/sim/bd_ebbb_srn_0.sv" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_8/sim/bd_ebbb_sawn_0.sv" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_9/sim/bd_ebbb_swn_0.sv" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_10/sim/bd_ebbb_sbn_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_11/sim/bd_ebbb_m00s2a_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/bd_0/ip/ip_12/sim/bd_ebbb_m00e_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_35 -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_21 -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_smartconnect_0_3/sim/secure_soc_smartconnect_0_3.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ipshared/909a/src/bus_to_axi.v" \
"../../../bd/secure_soc/ip/secure_soc_bus_axi_periph_0_5/sim/secure_soc_bus_axi_periph_0_5.v" \
"../../../bd/secure_soc/ip/secure_soc_ila_1_0/sim/secure_soc_ila_1_0.v" \
"../../../bd/secure_soc/sim/secure_soc.v" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/secure_soc/ip/secure_soc_proc_sys_reset_0_0/sim/secure_soc_proc_sys_reset_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/secure_soc/ip/secure_soc_clk_wiz_0_0/secure_soc_clk_wiz_0_0.v" \
"../../../bd/secure_soc/ip/secure_soc_xlconstant_0_0/sim/secure_soc_xlconstant_0_0.v" \

vlog -work util_vector_logic_v2_0_5 -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/e056/hdl/util_vector_logic_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a8e4/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/ec67/hdl" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/a9be" "+incdir+../../../../../2025.1/data/rsb/busdef" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/5431/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/4e08/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/537f/hdl/verilog" "+incdir+../../../../ibex_hello_world.gen/sources_1/bd/secure_soc/ipshared/d41f/hdl/verilog" "+incdir+/home/llia622/2025.1/Vivado/data/xilinx_vip/include" \
"../../../bd/secure_soc/ip/secure_soc_util_vector_logic_0_0/sim/secure_soc_util_vector_logic_0_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

